# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: > #Castle - hashtagcastle.com
email: me@jamiechung.me
description: > CHYEAH!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hashtagcastle.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  hashtagcastle

# Build settings
markdown: kramdown
